# Generated by Django 3.2.8 on 2021-11-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='num_copies',
            field=models.IntegerField(default=0),
        ),
    ]
